# Generated by Django 4.1.1 on 2022-09-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "animal_type",
                    models.CharField(
                        choices=[
                            ("Dog", "Dog"),
                            ("Cat", "Cat"),
                            ("Bear", "Bear"),
                            ("Rodent", "Rodent"),
                        ],
                        default="Dog",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("sex", models.CharField(max_length=100)),
                ("breed", models.CharField(max_length=100)),
                ("neutred", models.BooleanField(default=False)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("age", models.IntegerField(null=True)),
                ("weight", models.CharField(max_length=20)),
                (
                    "adoption_status",
                    models.CharField(
                        choices=[
                            ("Dog", "Dog"),
                            ("Cat", "Cat"),
                            ("Bear", "Bear"),
                            ("Rodent", "Rodent"),
                        ],
                        default="AVAILABLE",
                        max_length=10,
                    ),
                ),
                ("temperament", models.CharField(max_length=100)),
                ("likes", models.CharField(max_length=100)),
                ("fee", models.CharField(max_length=20)),
                ("location", models.CharField(max_length=100)),
            ],
        ),
    ]
