# Generated by Django 5.0.3 on 2024-04-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "animal_type",
                    models.CharField(
                        choices=[
                            ("Dog", "Dog"),
                            ("Cat", "Cat"),
                            ("Bear", "Bear"),
                            ("Rodent", "Rodent"),
                        ],
                        default="Dog",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("sex", models.CharField(max_length=100)),
                ("breed", models.CharField(max_length=100)),
                ("neutered", models.BooleanField(default=False)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("age", models.IntegerField(null=True)),
                ("weight", models.CharField(max_length=20)),
                (
                    "adoption_status",
                    models.CharField(
                        choices=[("AVAILABLE", "AVAILABLE"), ("ADOPTED", "ADOPTED")],
                        default="AVAILABLE",
                        max_length=10,
                    ),
                ),
                ("temperament", models.CharField(max_length=100)),
                ("likes", models.CharField(max_length=100)),
                ("fee", models.CharField(max_length=20)),
                ("location", models.CharField(max_length=100)),
                ("image", models.ImageField(default=None, upload_to="profile_images")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=50, unique=True)),
                ("username", models.CharField(max_length=50)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
