# Generated by Django 4.1.1 on 2023-11-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animal_rescue_api", "0002_animal_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="animal",
            old_name="neutred",
            new_name="neutered",
        ),
        migrations.AlterField(
            model_name="animal",
            name="adoption_status",
            field=models.CharField(
                choices=[("AVAILABLE", "AVAILABLE"), ("ADOPTED", "ADOPTED")],
                default="AVAILABLE",
                max_length=10,
            ),
        ),
    ]
